import type { Product, Category } from "./types"

export const categories: Category[] = [
  {
    id: "cat1",
    name: "Clothing",
    slug: "clothing",
    description: "Stylish and comfortable clothing for all occasions",
    image: "/placeholder.svg?height=600&width=600",
    productCount: 24,
  },
  {
    id: "cat2",
    name: "Footwear",
    slug: "footwear",
    description: "Trendy and comfortable footwear for all occasions",
    image: "/placeholder.svg?height=600&width=600",
    productCount: 18,
  },
  {
    id: "cat3",
    name: "Accessories",
    slug: "accessories",
    description: "Complete your look with our stylish accessories",
    image: "/placeholder.svg?height=600&width=600",
    productCount: 15,
  },
  {
    id: "cat4",
    name: "Electronics",
    slug: "electronics",
    description: "Latest gadgets and electronics for your lifestyle",
    image: "/placeholder.svg?height=600&width=600",
    productCount: 12,
  },
  {
    id: "cat5",
    name: "Home & Living",
    slug: "home-living",
    description: "Enhance your living space with our home collection",
    image: "/placeholder.svg?height=600&width=600",
    productCount: 20,
  },
  {
    id: "cat6",
    name: "Beauty",
    slug: "beauty",
    description: "Premium beauty products for your self-care routine",
    image: "/placeholder.svg?height=600&width=600",
    productCount: 16,
  },
]

export const products: Product[] = [
  {
    id: "prod1",
    name: "Premium Cotton T-Shirt",
    description: "Soft and comfortable cotton t-shirt for everyday wear",
    price: 29.99,
    image: "/placeholder.svg?height=600&width=600",
    categoryId: "cat1",
    isNew: true,
    colors: ["#000000", "#ffffff", "#ff0000", "#0000ff"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "prod2",
    name: "Slim Fit Jeans",
    description: "Classic slim fit jeans with a modern touch",
    price: 59.99,
    oldPrice: 79.99,
    image: "/placeholder.svg?height=600&width=600",
    categoryId: "cat1",
    discount: 25,
    colors: ["#000000", "#0000ff", "#808080"],
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "prod3",
    name: "Casual Sneakers",
    description: "Comfortable sneakers for your active lifestyle",
    price: 89.99,
    image: "/placeholder.svg?height=600&width=600",
    categoryId: "cat2",
    colors: ["#ffffff", "#000000", "#ff0000"],
    sizes: ["7", "8", "9", "10", "11"],
  },
  {
    id: "prod4",
    name: "Leather Wallet",
    description: "Genuine leather wallet with multiple card slots",
    price: 49.99,
    image: "/placeholder.svg?height=600&width=600",
    categoryId: "cat3",
    colors: ["#000000", "#8B4513"],
    sizes: ["OS"],
  },
  {
    id: "prod5",
    name: "Wireless Earbuds",
    description: "High-quality wireless earbuds with noise cancellation",
    price: 129.99,
    oldPrice: 149.99,
    image: "/placeholder.svg?height=600&width=600",
    categoryId: "cat4",
    isNew: true,
    colors: ["#000000", "#ffffff"],
    sizes: ["OS"],
  },
  {
    id: "prod6",
    name: "Scented Candle Set",
    description: "Set of 3 scented candles for a relaxing atmosphere",
    price: 34.99,
    image: "/placeholder.svg?height=600&width=600",
    categoryId: "cat5",
    colors: ["#F5F5DC", "#D3D3D3", "#FFE4E1"],
    sizes: ["OS"],
  },
  {
    id: "prod7",
    name: "Facial Serum",
    description: "Hydrating facial serum for all skin types",
    price: 24.99,
    image: "/placeholder.svg?height=600&width=600",
    categoryId: "cat6",
    colors: ["#F5F5DC"],
    sizes: ["30ml", "50ml"],
  },
  {
    id: "prod8",
    name: "Hooded Sweatshirt",
    description: "Warm and cozy hooded sweatshirt for cold days",
    price: 49.99,
    image: "/placeholder.svg?height=600&width=600",
    categoryId: "cat1",
    discount: 15,
    colors: ["#000000", "#808080", "#0000ff", "#008000"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
]

export const featuredProducts = products.filter((product) => product.isNew || product.discount)

